### PR TITLE
fix: new survey position for feedback button

### LINKED ISSUE #29773: Bug report: custom feedback button survey does not obey positioning customisation
### Bug Description

Created a survey based on a custom feedback button and customised the positioning to be "Center". However, in practice, the survey is sticking to the left. More information (including call recording with screenshots) in [this Slack message](https://posthog.slack.com/archives/C07QD3LT8U9/p1741370931708519)

Image

## Additional context

The feedback button is implemented in a VSCode plugin. The feedback button is not in the plugin page, instead it is on top of the plugin page – i.e. there is no physical button on the page where a class name can be added to PostHog. So the customer created an invisible button that gets 'clicked on' when user generates "feedback button clicked" event.

### Debug info

```shell
- [ ] PostHog Cloud, Debug information: [please copy/paste from https://us.posthog.com/settings/project-details#variables or https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]
```

### PR DESCRIPTION
**Pull request by lucasheriques**
## Changes

necessary to fix [this issue](https://github.com/PostHog/posthog/issues/29773). Will also require a change on the main app.

Verified locally positions are now working as expected:

image

### CODE REVIEW

File: src/posthog-surveys-types.ts [hunk 1]
```diff
@@ -10,6 +10,13 @@ export enum SurveyWidgetType {
     Selector = 'selector',
 }
 
+export enum SurveyPosition {
```
Comment (marandaneto) [inline src/posthog-surveys-types.ts:13]: nice

**Review by marandaneto — APPROVED** [review]

**Review by ioannisj — COMMENTED** [review]
What's that sample app in the screenshot? Is it available in the repo?

**Comment by marandaneto** [comment]
> What's that sample app in the screenshot? Is it available in the repo?

yes a few [here](https://github.com/PostHog/posthog-js/tree/main/playground)
