### PR TITLE
fix(ai): read tool-call input field in vercel non-streaming output

### LINKED ISSUE #3011: Tool call arguments missing in Vercel AI SDK v6 non-streaming output
## Bug description

When using `withTracing` with the Vercel AI SDK v6 and `generateText` (non-streaming), tool call arguments are logged as empty `"{}"` instead of the actual arguments. This is because `mapVercelOutput` looks for `item.args` or `item.arguments`, but Vercel AI SDK v6 uses `item.input` for tool call arguments.

### Environment

- `@posthog/ai`: 7.8.2
- `ai` (Vercel AI SDK): 6.0.57
- Node.js: 22.x

```typescript
import { withTracing } from "@posthog/ai";
import { generateText, tool } from "ai";
import { createOpenAI } from "@ai-sdk/openai";
import { PostHog } from "posthog-node";
import { z } from "zod";

const phClient = new PostHog("phc_xxx", { host: "https://eu.i.posthog.com" });
const openai = createOpenAI();

const myTool = tool({
  description: "A test tool",
  parameters: z.object({
    message: z.string(),
  }),
  execute: async (input) => input,
});

await generateText({
  model: withTracing(openai("gpt-4o"), phClient, {}),
  tools: { myTool },
  prompt: "Call myTool with message 'hello world'",
});
```

### Expected behavior

PostHog event should contain the tool call with arguments:
```json
{
  "type": "tool-call",
  "id": "call_xxx",
  "function": {
    "name": "myTool",
    "arguments": "{\"message\":\"hello world\"}"
  }
}
```

### Actual behavior

PostHog output event contains empty arguments:
```json
{
  "type": "tool-call",
  "id": "call_xxx",
  "function": {
    "name": "myTool",
    "arguments": "{}"
  }
}
```

### Root cause

In `src/vercel/middleware.ts`, the `mapVercelOutput` function (around line 208) looks for the wrong property:

```javascript
if (item.type === 'tool-call') {
  return {
    type: 'tool-call',
    id: item.toolCallId,
    function: {
      name: item.toolName,
      arguments: item.args || JSON.stringify(item.arguments || {})  // ❌ Wrong properties
    }
  };
}
```

Vercel AI SDK v6 uses `item.input` for tool call arguments, not `item.args` or `item.arguments`, see [migration guide](https://ai-sdk.dev/docs/migration-guides/migration-guide-5-0#tool-property-changes-argsresult--inputoutput).

**Note**: The streaming path in `doStream` correctly uses `toolCall.input` (line 583), and `mapVercelPrompt` also correctly uses `c.input` (line 139). Only `mapVercelOutput` has this bug.

### Suggested fix

```javascript
if (item.type === 'tool-call') {
  return {
    type: 'tool-call',
    id: item.toolCallId,
    function: {
      name: item.toolName,
      arguments: item.input || item.args || JSON.stringify(item.arguments || {})  // ✅ Check item.input first
    }
  };
}
```

## Related sub-libraries

- [ ] All of them
- [ ] posthog-js (web)
- [ ] posthog-js-lite (web lite)
- [ ] posthog-node
- [ ] posthog-react-native
- [ ] @posthog/react
- [x] @posthog/ai
- [ ] @posthog/nextjs-config
- [ ] @posthog/nuxt
- [ ] @posthog/rollup-plugin
- [ ] @posthog/webpack-plugin

### PR DESCRIPTION
**Pull request by richardsolomou**
## Problem

When using `withTracing` with Vercel AI SDK v6 and `generateText` (non-streaming), tool call arguments were logged as empty `"{}"` in `$ai_output_choices` instead of the actual arguments. Affects anyone tracking tool-calling agents with `@posthog/ai` + `ai@^6`.

Root cause: `mapVercelOutput` in `packages/ai/src/vercel/middleware.ts` looked for `item.args` / `item.arguments`, but AI SDK v5+ emits tool-call content parts with `item.input` (a stringified JSON, per `LanguageModelV{2,3}ToolCall` in `@ai-sdk/provider`). The streaming path and `mapVercelPrompt` already read `input` correctly — only the non-streaming output mapping was wrong.

Fixes #3011.

## Changes

- `mapVercelOutput` now reads `item.input` first, falling back to `item.args` / `item.arguments` for older AI SDK versions. When `input` is an object (non-conforming providers), it is `JSON.stringify`d to produce the string shape `$ai_output_choices` expects.
- Added a parameterised test covering both string-input (per spec) and object-input (defensive) cases for V3 non-streaming tool calls.

### Libraries affected

- [ ] All of them
- [ ] posthog-js (web)
- [ ] posthog-js-lite (web lite)
- [ ] posthog-node
- [ ] posthog-react-native
- [ ] @posthog/react
- [x] @posthog/ai
- [ ] @posthog/convex
- [ ] @posthog/next
- [ ] @posthog/nextjs-config
- [ ] @posthog/nuxt
- [ ] @posthog/rollup-plugin
- [ ] @posthog/webpack-plugin
- [ ] @posthog/types

## Checklist

- [x] Tests for new code
- [x] Accounted for the impact of any changes across different platforms
- [x] Accounted for backwards compatibility of any changes (no breaking changes!)
- [x] Took care not to unnecessarily increase the bundle size

### If releasing new changes

- [x] Ran `pnpm changeset` to generate a changeset file
- [x] Added the "release" label to the PR to indicate we're publishing new versions for the affected packages

---
*Created with [PostHog Code](https://posthog.com/code?ref=pr)*

### CODE REVIEW

File: packages/ai/src/vercel/middleware.ts [hunk 1]
```diff
@@ -200,12 +200,13 @@ const mapVercelOutput = (result: LanguageModelContent[]): PostHogInput[] => {
       return { type: 'text', text: truncate(item.text) }
     }
     if (item.type === 'tool-call') {
+      const rawArgs = (item as any).input ?? (item as any).args ?? (item as any).arguments ?? {}
```
Comment (carlos-marchal-ph) [inline packages/ai/src/vercel/middleware.ts]: The three `as any` casts could collapse into one narrow assertion, since `item` is already narrowed to the tool-call variants in this branch and V3 already types `input` as `unknown`:

```ts
const toolCall = item as { input?: unknown; args?: unknown; arguments?: unknown }
const rawArgs = toolCall.input ?? toolCall.args ?? toolCall.arguments ?? {}
```

File: packages/ai/tests/vercel.test.ts [hunk 2]
```diff
@@ -373,6 +373,59 @@ describe('Vercel AI SDK - Dual Version Support', () => {
         },
       ])
     })
+
+    it.each([
+      ['string input (per spec)', '{"message":"hello world"}'],
```
Comment (carlos-marchal-ph) [inline packages/ai/tests/vercel.test.ts]: The `args` and `arguments` fallbacks have no test coverage, so if they get dropped in a future refactor the regression would be silent. Worth a third `it.each` row feeding something like `args: '{"a":1}'` on the mock content part?

File: packages/ai/tests/vercel.test.ts [hunk 3]
```diff
@@ -373,6 +373,59 @@ describe('Vercel AI SDK - Dual Version Support', () => {
...
+      }
+
+      const model = withTracing(baseModel, mockPostHogClient, {
+        posthogDistinctId: 'test-user',
+        posthogTraceId: 'test-v3-tool-input',
+      })
+
+      await model.doGenerate({
+        prompt: [{ role: 'user' as const, content: [{ type: 'text' as const, text: 'Call myTool' }] }],
+      } as any)
```
Comment (carlos-marchal-ph) [inline packages/ai/tests/vercel.test.ts]: Could this use `LanguageModelV3CallOptions` instead of `as any`? Would keep the test honest to the public type surface if the shape changes upstream.

**Review by carlos-marchal-ph — APPROVED** [review]

File: packages/ai/src/vercel/middleware.ts (hunk 1 above)
Comment (richardsolomou) [reply packages/ai/src/vercel/middleware.ts]: Done in d4736d58 — collapsed into a single `{ input?: unknown; args?: unknown; arguments?: unknown }` assertion.

File: packages/ai/tests/vercel.test.ts (hunk 2 above)
Comment (richardsolomou) [reply packages/ai/tests/vercel.test.ts]: Good catch — added rows for `args: "<string>"` and `arguments: { ... }` in d4736d58, so both fallback paths are now covered.

File: packages/ai/tests/vercel.test.ts (hunk 3 above)
Comment (richardsolomou) [reply packages/ai/tests/vercel.test.ts]: Switched to `LanguageModelV3CallOptions` in d4736d58.
