### PR TITLE
fix(surveys): guard eligibility checks against storage access errors

### LINKED ISSUE #3324: Surveys feature errors if `localStorage` is not available
## Bug description

We're getting lots of errors in Sentry coming from the surveys feature with the following signature:

```
TypeError: Cannot read properties of null (reading 'getItem')
```

coming from `Rt.checkSurveyEligibility` according to the stack trace.

All reports have come from the Chrome Mobile WebView browser except one which came from Twitter.

## How to reproduce

Not sure exactly but it would seem that enabling the survey feature and visiting in a WebView browser will do it.

## Related sub-libraries

- [ ] All of them
- [x] posthog-js (web)
- [ ] posthog-js-lite (web lite)
- [ ] posthog-node
- [ ] posthog-react-native
- [ ] @posthog/react
- [ ] @posthog/ai
- [ ] @posthog/convex
- [ ] @posthog/nextjs-config
- [ ] @posthog/nuxt
- [ ] @posthog/rollup-plugin
- [ ] @posthog/webpack-plugin

### PR DESCRIPTION
**Pull request by marandaneto**
## Problem

Survey eligibility checks currently read directly from `localStorage`, which can throw in some browser/storage-restricted environments. When that happens, survey wait-period and seen-state checks can fail instead of safely treating the survey as unseen.

Closes https://github.com/PostHog/posthog-js/issues/3324

## Changes

- switched survey seen/wait-period reads in `surveys-extension-utils.tsx` to use `localStore._get(...)` so storage access failures are handled safely
- wrapped `setSurveySeenOnLocalStorage` in a `try/catch` and log persistence failures instead of throwing
- added regression tests covering `localStorage.getItem` throwing for both `hasWaitPeriodPassed` and `getSurveySeen`
- included a patch changeset for `posthog-js`

### Libraries affected

- [ ] All of them
- [x] posthog-js (web)
- [ ] posthog-js-lite (web lite)
- [ ] posthog-node
- [ ] posthog-react-native
- [ ] @posthog/react
- [ ] @posthog/ai
- [ ] @posthog/convex
- [ ] @posthog/next
- [ ] @posthog/nextjs-config
- [ ] @posthog/nuxt
- [ ] @posthog/rollup-plugin
- [ ] @posthog/webpack-plugin
- [ ] @posthog/types

## Checklist

- [x] Tests for new code
- [x] Accounted for the impact of any changes across different platforms
- [x] Accounted for backwards compatibility of any changes (no breaking changes!)
- [x] Took care not to unnecessarily increase the bundle size

### If releasing new changes

- [x] Ran `pnpm changeset` to generate a changeset file
- [x] Added the "release" label to the PR to indicate we're publishing new versions for the affected packages

### CODE REVIEW

File: packages/browser/src/utils/survey-utils.ts [hunk 1]
```diff
@@ -48,13 +48,18 @@ export const getSurveyAbandonedKey = (survey: Pick<Survey, 'id' | 'current_itera
...
 
 export const setSurveySeenOnLocalStorage = (survey: Pick<Survey, 'id' | 'current_iteration'>) => {
-    const isSurveySeen = localStorage.getItem(getSurveySeenKey(survey))
-    // if survey is already seen, no need to set it again
-    if (isSurveySeen) {
-        return
-    }
+    try {
+        const surveySeenKey = getSurveySeenKey(survey)
+        const isSurveySeen = localStorage.getItem(surveySeenKey)
```
Comment (lucasheriques) [inline packages/browser/src/utils/survey-utils.ts:53]: i imagine there's a reason to not use `localStore` here too, like above, just not sure why 🤔

**Review by lucasheriques — APPROVED** [review]
thank you!

File: packages/browser/src/utils/survey-utils.ts (hunk 1 above)
Comment (marandaneto) [reply packages/browser/src/utils/survey-utils.ts:53]: uf auto merge was on
this is a port from https://github.com/PostHog/posthog-js/pull/3350 so i didnt change anything else
i believe they just fixed where the errors were happening
