### PR TITLE
Do not crash when calling capture() after skipping init(), fixes #281

### LINKED ISSUE #281: crash in _captureMetrics if init is skipped in during development
**Context**
I am using PostHog within the Gatsby framework.  I am _not_ using the snippet installation, but instead importing as a module.

posthog-js version: 1.13.7
Browser: Chrome Version 92.0.4515.131 (Official Build) (x86_64)

**Problem**
In development, I skip `posthog.init` on localhost (as the [docs](https://posthog.com/docs/integrate/client/js) imply you can), but I still would like to sprinkle calls to `posthog.capture` throughout the code.  When I do call posthog.capture, I get an error, attached below - implying there is an uninitialized variable [this._captureMetrics](https://github.com/PostHog/posthog-js/blob/a6960bbdf252de2b93347dbcf196a686e5132747/src/posthog-core.js#L534)

image

**What I expected to happen**
I didn't expect `posthog.capture` to fail when I called it without initializing, I expected it to be a noop essenitally. Which would allow me to write succinct code for custom events.

```javascript
// I expected to be able to write code like this
const onVeryImportantClick = () => {
  posthog.capture('important-event', { very: 'important', data: true });
};

// not like this
const onVeryImportantClick = () => {
  if (some.config.someehwere.posthogEnabled) {
    posthog.capture('important-event', { very: 'important', data: true });
  }
};
```

Fixing the issue doesn't seem to be a big deal, but I'm not sure if not conceptually understanding posthog incorrectly, didn't understand the docs, or if this is a legitimate bug.  If the latter, I am more than happy to fix it.  Just looking for a project maintainer to give a little bit of guidance.

### PR DESCRIPTION
**Pull request by skabbes**
## Bug
When developing on localhost - the [docs](https://posthog.com/docs/integrate/client/js) suggest to skip `posthog.init()` entirely.  However, when you do - any calls to posthog.capture throw.  More details here https://github.com/PostHog/posthog-js/issues/281

## Root Cause
Since `init_as_module` seems to purposefully skips library initialization (and therefore not set `__loaded` or `_captureMetrics` or several other critical members of the PostHogLib class).  Calling instance methods (like capture) on an uninitialized library causes it to throw.

## Changes
Simply checking `posthog.__loaded` can allow any of these methods to noop safely.

## Next Steps
There were several other instance methods that would likely throw if used (I just have no encountered them in my app so far).  At the very least, identify likely does as well.

## Checklist
- [X] Tests for new code (if applicable)
- [X] TypeScript definitions (module.d.ts) updated and in sync with library exports (if applicable)

### CODE REVIEW

File: src/__tests__/posthog-core.js [hunk 1]
```diff
@@ -141,6 +141,7 @@ describe('capture()', () => {
     )
 
     given('overrides', () => ({
+        __loaded: true,
```
Comment (skabbes) [inline src/__tests__/posthog-core.js:144]: Without this change, these test would fail.  The only reason they actually were not failing before, was because `_captureMetrics` was being specifically overridden a few lines down.

**Comment by mariusandra** [comment]
Hey, while this works, it can be pretty scary to swallow errors. It could be quite likely to get to a scenario where the developer just forgot to `init`, instead of consciously omitting it, and would like to be notified of this. The current "it just breaks" option works well to bring urgency to this case.

Perhaps this is resolved by just showing a big warning if running posthog-js without `init`, or alternatively call `posthog.opt_out_capturing();` right after `init` (with some mock API/token?) when developing to not make any real API calls.

**Comment by skabbes** [comment]
Hey Marius, thanks for looking at this.

I confirmed with Tim in my issue filed that a noop was an acceptable solution. https://github.com/PostHog/posthog-js/issues/281  but sounds like you'd like a different one. I think high level, I'll just wait to write any more code until the team decides what to do.

Regardless of the solution, I'd like to be able to use posthog (including calls to `capture` in my code) without having work around the posthog's decision to crash.  Any solution that solves that if fine with me, and I'll respect the Posthog team's decision on the matter, but crashing is certainly not acceptable - for a documented feature of the library.

But I will offer my (unsolicited) thoughts on how _I_ would build it (open source ftw :) )

> it can be pretty scary to swallow errors

Yes, agree - but I don't think I'd call "following the documented way to skip test sending data on localhost" an error.  I appreciate always trying to encourage developers to do the right thing with helpful warnings and errors - but right now, you cannot tell the difference between purposefully skipping init, and accidentally skipping init. You are suggesting to _harm_ the developer who read the docs, and purposefully _help_ the one who didn't.  That's the **not** tradeoff I'd personally make (for a tool that's marketed as open source, and privacy centric). But... its also not my product :)
 
I'd say even scarier when you know your analytics software might throw an exception at any time.  I'd rather have my site work and not have any analytics (due to a fault of my own). Then have my site break (and still not have any analytics) by following the documented way to disable sending data.

**I think at the end of the day, this is possibly just a documentation bug.**  and I would certainly and defer to the posthog team's judgement on how to support my usecase of "I want to disable posthog during development, QA, etc - without having to have a custom written posthog wrapper in my own codebase".

I'm looking forward to a solution - and would be happy to help write it, if the posthog team can come to a consensus about _how_ to solve it.

**Comment by bard** [comment]
Just to add a data point: in developing a React app with feature flags, I'm currently stuck between these options, none of which seems ideal:

1. Sending metrics in dev plus making posthog a hard dependency of the UI (i.e. if posthog isn't accessible, the UI crashes)
2. Giving up feature flags
3. Replace `useFeatureFlags`/`PostHogProvider` with custom ones that detect if the posthog client has been initialized and recover if it hasn't (did it on another project... wasn't pretty)

**Review by mariusandra — APPROVED** [review]
Ok, let's get this in.
