### PR TITLE
Fix sessionRecording bug

### LINKED ISSUE #183: Posthog-js sending requests to /sessionRecording on user's own servers
I got a report from a user that they are seeing 404 requests to `/sessionRecording` on their own servers, when using app.posthog.com. So the requests are to theirdomain.com/sessionRecording

image

@macobo any idea why this might be happening? I had a quick grep through the codebase but nothing obvious.

### PR DESCRIPTION
**Pull request by neilkakkar**
## Changes

Fixes #183 

What a rollercoaster! The `url` is just one of many possible values for the key in the request object, the other possible options being: `batchKey`, which, ofcourse, we set to `sessionRecording` for session recording! ( https://github.com/PostHog/posthog-js/blob/master/src/extensions/sessionrecording.js#L122 )

The annoying bit was figuring out that it was this specific part of the request queue that was mangling things up.

...

## Checklist
- [x] Tests for new code (if applicable)
- [x] TypeScript definitions (module.d.ts) updated and in sync with library exports (if applicable)

### CODE REVIEW

**Review by timgl — APPROVED** [review]

File: src/request-queue.js [hunk 1]
```diff
@@ -87,8 +87,8 @@ export class RequestQueue {
         clearTimeout(this._poller)
         const requests = this._event_queue.length > 0 ? this.formatQueue() : {}
         this._event_queue.length = 0
-        for (let url in requests) {
-            const { data, options } = requests[url]
+        for (let key in requests) {
+            const { url, data, options } = requests[key]
```
Comment (macobo) [inline src/request-queue.js:91]: Interesting. There are tests under src/__tests__/request-queue.js - mind adding one or editing existing ones in a way which demonstrates the problem? E.g. how was enqueue called in this case?

Comment (neilkakkar) [reply src/request-queue.js:91]: Sure thing, that was the first item for today!

It's kinda unfortunate: we had a similar test for poll that works, but didn't have one for unload.

File: src/__tests__/request-queue.js [hunk 2]
```diff
@@ -83,4 +83,32 @@ describe('RequestQueue', () => {
...
+                { event: 'bar', timestamp: 1_630_000_000 },
+            ],
+            { transport: 'sendbeacon' }
+        )
+        expect(given.handlePollRequest).toHaveBeenCalledWith(
+            '/identify',
+            [{ event: '$identify', timestamp: 1_620_000_000 }],
+            { transport: 'sendbeacon' }
+        )
+        expect(given.handlePollRequest).toHaveBeenCalledWith('/e', [{ event: 'zeta', timestamp: 1_640_000_000 }], {
```
Comment (neilkakkar) [inline src/__tests__/request-queue.js:109]: with the old code, this would be called with `('sessionRecording', data, options)`

**Review by macobo — APPROVED** [review]

**Comment by macobo** [comment]
Great detective work! Reminder: don't forget to set `bump X` label before merging
