### PR TITLE
fix: surveys on react native web renders and get focused correctly

### LINKED ISSUE #2295: Survey TextInput is not focusable due to 'Unexpected text node' rendering error posthog-react-native
## Bug description

The rating/NPS part of a survey works, but the subsequent open-ended text input cannot be focused or typed in.

This appears to be the root cause: https://stackoverflow.com/questions/72072640/react-native-unexpected-text-node-a-text-node-cannot-be-a-child-of-a-view/72072813

## Related sub-libraries

- [ ] All of them
- [ ] posthog-js (web)
- [ ] posthog-js-lite (web lite)
- [ ] posthog-node
- [x] posthog-react-native
- [ ] @posthog/react
- [ ] @posthog/ai
- [ ] @posthog/nextjs-config

## Additional context
"posthog-react-native": "^4.5.0",
"react-native": "0.79.5",

Console log:
Unexpected text node: . A text node cannot be a child of a <View>. Error Component Stack
    at View (entry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.routerRoot=app:9814:27)
    at QuestionHeader (entry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.routerRoot=app:94746:25)
    at RatingQuestion (entry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.routerRoot=app:94297:26)
    at div (<anonymous>)
    at View (entry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.routerRoot=app:9814:27)
    at div (<anonymous>)
    at View (entry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.routerRoot=app:9814:27)
    at entry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.routerRoot=app:7027:26
    at ScrollView (entry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.routerRoot=app:5731:7)
    at ScrollView (<anonymous>)
    at Questions (entry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.routerRoot=app:93819:23)
    at div (<anonymous>)
    at View (entry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.routerRoot=app:9814:27)
    at div (<anonymous>)
    at View (entry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.routerRoot=app:9814:27)
    at TouchableWithoutFeedback (entry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.routerRoot=app:42629:30)
    at div (<anonymous>)
    at View (entry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.routerRoot=app:9814:27)
    at KeyboardAvoidingView (entry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.routerRoot=app:39968:7)
    at div (<anonymous>)
    at View (entry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.routerRoot=app:9814:27)
    at div (<anonymous>)
    at View (entry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.routerRoot=app:9814:27)
    at entry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.routerRoot=app:40323:24
    at div (<anonymous>)
    at View (entry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.routerRoot=app:9814:27)
    at ModalFocusTrap (entry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.routerRoot=app:40443:23)
    at div (<anonymous>)
    at ModalAnimation (entry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.routerRoot=app:40179:31)
    at ModalPortal (entry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.routerRoot=app:40125:26)
    at entry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.routerRoot=app:40057:31
    at SurveyModal (entry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.routerRoot=app:95116:24)
    at PostHogSurveyProvider (entry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.routerRoot=app:93643:54)
    at div (<anonymous>)
    at View (entry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.routerRoot=app:9814:27)
    at PostHogProvider (entry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.routerRoot=app:93301:26)
    at RootLayout (entry.bundle?platform=web&dev=true&hot=false&lazy=true&transform.routerRoot=app:43153:50)

### PR DESCRIPTION
**Pull request by marandaneto**
## Problem

Closes https://github.com/PostHog/posthog-js/issues/2295#issuecomment-3285201420

### Libraries affected

- [ ] All of them
- [ ] posthog-js (web)
- [ ] posthog-js-lite (web lite)
- [ ] posthog-node
- [X] posthog-react-native
- [ ] @posthog/react
- [ ] @posthog/ai
- [ ] @posthog/nextjs-config

## Checklist

- [ ] Tests for new code
- [x] Accounted for the impact of any changes across different platforms
- [x] Accounted for backwards compatibility of any changes (no breaking changes!)
- [ ] Took care not to unnecessarily increase the bundle size

### If releasing new changes

- [x] Ran `pnpm changeset` to generate a changeset file
- [x] Added the "release" label to the PR to indicate we're publishing new versions for the affected packages

### CODE REVIEW

File: packages/react-native/src/surveys/components/SurveyModal.tsx [hunk 1]
```diff
@@ -55,7 +55,7 @@ export function SurveyModal(props: SurveyModalProps): JSX.Element | null {
         <TouchableWithoutFeedback onPress={Keyboard.dismiss} accessible={false}>
           <View style={styles.modalBackdrop}>
             <Pressable style={StyleSheet.absoluteFill} onPress={onClose} accessible={false} />
-            <View
+            <Pressable
```
Comment (marandaneto) [inline packages/react-native/src/surveys/components/SurveyModal.tsx]: there's a Pressable with StyleSheet.absoluteFill that covers the entire modal and has an onPress={onClose} handler. This overlay is intercepting all touch events, preventing the TextInput from receiving focus

File: packages/react-native/src/surveys/components/ConfirmationMessage.tsx [hunk 2]
```diff
@@ -24,11 +24,17 @@ export function ConfirmationMessage({
...
+      ? description.replace(/<[^>]*>/g, '') // Strip HTML tags for React Native
+      : description
+    : null
+
   return (
     <View style={styleOverrides}>
       <View style={styles.thankYouMessageContainer}>
         <Text style={[styles.thankYouMessageHeader, { color: textColor }]}>{header}</Text>
-        {description && contentType === SurveyQuestionDescriptionContentType.Text && <Text>{description}</Text>}
+        {processedDescription && <Text>{processedDescription}</Text>}
```
Comment (marandaneto) [inline packages/react-native/src/surveys/components/ConfirmationMessage.tsx]: When contentType is HTML, the description is not being rendered but when it's not defined or is HTML, it might render raw HTML content

File: packages/browser/src/extensions/surveys/icons.tsx [hunk 3]
```diff
@@ -34,8 +34,8 @@ export const cancelSVG = (
     >
         <title id="close-survey-title">Close survey</title>
         <path
-            fill-rule="evenodd"
-            clip-rule="evenodd"
+            fillRule="evenodd"
+            clipRule="evenodd"
```
Comment (marandaneto) [inline packages/browser/src/extensions/surveys/icons.tsx]: warnings on browser, prob a typo

File: packages/react-native/src/surveys/components/SurveyModal.tsx [hunk 4]
```diff
@@ -1,14 +1,5 @@
 import React, { useCallback, useEffect, useState } from 'react'
-import {
-  Keyboard,
-  KeyboardAvoidingView,
-  Modal,
-  Platform,
-  Pressable,
-  StyleSheet,
-  TouchableWithoutFeedback,
```
Comment (marandaneto) [inline packages/react-native/src/surveys/components/SurveyModal.tsx:9]: TouchableWithoutFeedback is deprecated, so removed altogether

File: packages/react-native/src/surveys/components/SurveyModal.tsx [hunk 5]
```diff
@@ -96,13 +88,18 @@ const styles = StyleSheet.create({
...
+    width: '90%',
+    maxWidth: 400,
+  },
+  modalContentInner: {
     borderRadius: 10,
     borderWidth: 1,
     padding: 20,
-    width: '90%',
-    maxWidth: 400,
-    marginHorizontal: 20,
```
Comment (marandaneto) [inline packages/react-native/src/surveys/components/SurveyModal.tsx:105]: so only the modal view is clicklable and dismissable via the X or Submit/Close buttons
before the whole sides were dismissing the survey which was weird

File: packages/react-native/src/surveys/components/ConfirmationMessage.tsx [hunk 6]
```diff
@@ -24,11 +24,17 @@ export function ConfirmationMessage({
 }): JSX.Element {
   const textColor = getContrastingTextColor(appearance.backgroundColor)
 
+  const processedDescription = description
+    ? contentType === SurveyQuestionDescriptionContentType.Html
+      ? description.replace(/<[^>]*>/g, '') // Strip HTML tags for React Native
+      : description
+    : null
+
```
Comment (lucasheriques) [inline packages/react-native/src/surveys/components/ConfirmationMessage.tsx]:
```
const processDescription = (description: string | null, contentType: SurveyQuestionDescriptionContentType) => {
  if (!description) return null;
  
  return contentType === SurveyQuestionDescriptionContentType.Html
    ? description.replace(/<[^>]*>/g, '')
    : description;
};

const processedDescription = processDescription(description, contentType);
```

minor suggestion to define a shared function since it's used in the QuestionHeader too. this function would live in a utils file somewhere

**Review by lucasheriques — APPROVED** [review]
looks good, left one suggestion
